'use strict';

function buildHeader(profile, definition) {
    let header = [
        `//------------------------------`,
        `// <auto-generated>`,
        `//     Generated using the Swagen tool`,
        `//     Generator: ${profile.generator}`
    ];
    if (profile.mode) {
        header.push(`//     Mode: ${profile.mode}`);
    }
    header.push(
        `// </auto-generated>`,
        `//------------------------------`
    );
    if (definition && definition.metadata) {
        if (definition.metadata.title) {
            header.push(`// ${definition.metadata.title}`);
        }
        if (definition.metadata.description) {
            header.push(`// ${definition.metadata.description}`);
        }
        if (definition.metadata.baseUrl) {
            header.push(`// Base URL: ${definition.metadata.baseUrl}`);
        }
    }
    return header;
}

module.exports = buildHeader;
